services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: unless-stopped
    volumes:
      - nexus-data:/nexus-data
    expose:
      - "8081"
    networks:
      - school_network

  nginx:
    image: nginx:alpine
    container_name: nexus-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/nexus.crt:/etc/nginx/certs/nexus.crt:ro
      - ./certs/nexus.key:/etc/nginx/certs/nexus.key:ro
    networks:
      - school_network
    depends_on:
      nexus:
        condition: service_started

volumes:
  nexus-data:

networks:
  school_network:
    driver: bridge
    external: true