server:
  port: 8085

spring:
  config:
    import: optional:configtree:/run/secrets/
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/auth-service-db
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      group-id: users
      auto-offset-reset: earliest
      enable-auto-commit: false

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

      properties:
        spring.json.trusted.packages: "*"

  grpc:
    client:
      channel:
        schoolStructure:
          target: static://${SCHOOL_STRUCTURE_HOST:localhost}:${SCHOOL_STRUCTURE_GRPC_PORT:9090}
          negotiation-type: plaintext

    server:
      port: -1

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-ms: 900000

springdoc:
  api-docs:
    path: /docs/auth/v3/api-docs
  swagger-ui:
    path: /docs/auth/swagger-ui.html