server:
  port: 8085

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/auth-service-db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET:VvyRVvEHvgAySvx17fYT6sCr1AXkuDvW66uiuFDwfVP}
  access-token-validity-ms: 900000