services:
  schedule-service:
    build: ./
    container_name: schedule-service
    restart: unless-stopped
    networks:
      - school_network
    environment:
      DB_HOST: schedule-service-db
      SCHOOL_STRUCTURE_HOST: school-structure-service
      SCHOOL_STRUCTURE_GRPC_PORT: 9090
    ports:
      - "8083:8083"
    depends_on:
      schedule-service-db:
        condition: service_healthy

  schedule-service-db:
    image: postgres:16-alpine
    container_name: schedule-service-db
    restart: unless-stopped
    networks:
      - school_network
    environment:
      POSTGRES_DB: schedule-service-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - schedule_service_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d schedule-service-db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  schedule_service_data:

networks:
  school_network:
    driver: bridge
    external: true